# SPDX-License-Identifier: MPL-2.0
apiVersion: v1
kind: Service
metadata:
  name: network-dashboard
  namespace: flatracoon-dashboard
  labels:
    app.kubernetes.io/name: network-dashboard
    app.kubernetes.io/part-of: flatracoon
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: network-dashboard
  ports:
    - name: http
      port: 4000
      targetPort: http
      protocol: TCP
